# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

# install:            # Install requirement as "Environment Setup Section"
# - pip install -r sphinx_root/requirements.txt

script:             # build sphinx document
- cd docs/
- make html
- cd -
deploy              # deploy to github page
- provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
