# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"
    - "3.7"

install:            # Install requirement as "Environment Setup Section"
    - pip install -r requirements.txt

script:             # build sphinx document
    - flake8
    - isort -rc --check-only --diff torchutils/
    - yapf -r -d --style .style.yapf torchutils/
    - cd docs/
    - make html

deploy:              # deploy to github page
    provider: pages
    skip_cleanup: true
    local_dir: docs/_build/html
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
